### ISSUE TITLE
ie11 technical prod address not working

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#2072]
When opening a technical prod url (p.e. http://mf-geoadmin3.prod.bgdi.ch/?X=190000.00&Y=660000.00&zoom=0&lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe ) with ie 11 the following error occurrs:

```
HTML1300: Navigation wurde ausgeführt.
Datei: mf-geoadmin3.prod.bgdi.ch
Error: Zugriff verweigert

   at Anonymous function (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:110:379)
   at m (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:107:168)
   at Anonymous function (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:104:428)
   at Anonymous function (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:136:242)
   at k.prototype.$eval (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:150:109)
   at k.prototype.$digest (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:147:210)
   at k.prototype.$apply (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:150:385)
   at m (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:106:1)
   at N (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:110:68)
   at w.onload (http://mf-geoadmin3.prod.bgdi.ch/1420635330/lib/build.js:111:104)

```

int and dev links are working fine.

**Comment by oterral** [comment]
CORS issue ?

**Comment by gjn** [comment]
Yes, it seems security settings of IE interfering here. IE11 (could only test inside IT network) seems to block *.admin.ch access from *.bgdi.ch domains. So here's the thing.

mf-geoadmin3.int.bgdi.ch needs mf-chsdi3.int.bgdi.ch -> works, because same domain
map.geo.admin.ch needs api3.geo.admin.ch -> works, because same domain
mf-geoadmin3.prod.bgdi.ch needs api3.geo.admin.ch -> does not work, because different domain.

We could try to add *.bgdi.ch to trusted domains of our settings through IT...

@ltclm Can we live with this issue? What's the use case to use the technical address?

**Comment by oterral** [comment]
*.bgdi.ch has been added to the trusted site of IE so it works now (after restart of computer)
