### ISSUE TITLE
[KML] Print kml fails

### ISSUE THREAD

**Issue by kandre** [geoadmin/mf-geoadmin3#2154]
Print kml fails on all browsers

Console log:
 
TypeError: Cannot set property '_gx_style' of undefined
    at http://map.geo.admin.ch/1423674319/lib/build.js:1479:310
    at Object.r [as forEach] (http://map.geo.admin.ch/1423674319/lib/build.js:32:302)
    at d.encoders.layers.Vector (http://map.geo.admin.ch/1423674319/lib/build.js:1478:241)
    at w (http://map.geo.admin.ch/1423674319/lib/build.js:1474:194)
    at http://map.geo.admin.ch/1423674319/lib/build.js:1484:40
    at Array.forEach (native)
    at Oa (http://map.geo.admin.ch/1423674319/lib/build.js:301:552)
    at C.l.forEach (http://map.geo.admin.ch/1423674319/lib/build.js:367:485)
    at Object.r [as forEach] (http://map.geo.admin.ch/1423674319/lib/build.js:32:354)
    at k.d.submit (http://map.geo.admin.ch/1423674319/lib/build.js:1483:367)

**Comment by oterral** [comment]
can you send me the kml file pls

**Comment by kandre** [comment]
Actually the print fails with any kml (and with the drawing too)

**Comment by oterral** [comment]
Totally right, it's caused by the update of ol.
