### ISSUE TITLE
Problem install 

### ISSUE THREAD

**Issue by UserGis** [geoadmin/mf-geoadmin3#2562]
I  download mf-geoadmin3,but when I run make all I am getting this error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: com.google.javascript.jscomp.CommandLineRunner. Program will exit.
make: *** [.build-artefacts/app.js] Error 1

**Comment by oterral** [comment]
@UserGis  install java 7 I guess see https://lifeforcode.wordpress.com/2015/01/09/how-to-fix-error-closure-compiler-unsupported-major-minor-version-51-0/
