### ISSUE TITLE
Error message after usage for measurement tool in layermanager

### ISSUE THREAD

**Issue by Jenselme** [geoadmin/mf-geoadmin3#2980]
Linked to #2975. The cause of the bugs are the same, I have the same ideas for solution. I think we should expect to be bitten because of this quite often.

How to reproduce:

- Enable draw & measure on map
- Use the measurement tool
- Disable draw & measure on map

Problems:
- Try to hide the layer. I get in the Chrome console (caused by `for (var i in features)` in https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/measure/MeasureService.js, 4 ocurences than may cause the bug) :
```
TypeError: olFeature.get is not a function
    at Object.isMeasureFeature (http://dev.geojb/components/map/MapService.js:1748:54)
    at null.<anonymous> (http://dev.geojb/components/measure/MeasureService.js:268:32)
    at goog.events.EventTarget.fireListeners (http://dev.geojb/lib/ol3cesium-debug.js:11841:23)
    at Function.goog.events.EventTarget.dispatchEventInternal_ (http://dev.geojb/lib/ol3cesium-debug.js:11938:26)
    at goog.events.EventTarget.dispatchEvent (http://dev.geojb/lib/ol3cesium-debug.js:11753:34)
    at ol.Object.notify (http://dev.geojb/lib/ol3cesium-debug.js:12277:8)
    at ol.Object.set (http://dev.geojb/lib/ol3cesium-debug.js:12297:12)
    at ol.layer.Base.setVisible (http://dev.geojb/lib/ol3cesium-debug.js:19939:8)
    at Object.defineProperties.visible.set (http://dev.geojb/components/map/MapService.js:94:22)
    at fn.assign (eval at <anonymous> (http://dev.geojb/lib/angular.js:13145:15), <anonymous>:4:410)
```
- Try to modify the transparency of the layer. I get in the Chrome console (caused by `for (var i in overlays)` in MeasureServices again):
```
TypeError: overlays[i].getElement is not a function
    at null.<anonymous> (http://dev.geojb/components/measure/MeasureService.js:284:33)
    at goog.events.EventTarget.fireListeners (http://dev.geojb/lib/ol3cesium-debug.js:11841:23)
    at Function.goog.events.EventTarget.dispatchEventInternal_ (http://dev.geojb/lib/ol3cesium-debug.js:11938:26)
    at goog.events.EventTarget.dispatchEvent (http://dev.geojb/lib/ol3cesium-debug.js:11753:34)
    at ol.Object.notify (http://dev.geojb/lib/ol3cesium-debug.js:12277:8)
    at ol.Object.set (http://dev.geojb/lib/ol3cesium-debug.js:12297:12)
    at ol.layer.Base.setOpacity (http://dev.geojb/lib/ol3cesium-debug.js:19928:8)
    at Object.defineProperties.invertedOpacity.set (http://dev.geojb/components/map/MapService.js:120:20)
    at fn.assign (eval at <anonymous> (http://dev.geojb/lib/angular.js:13145:15), <anonymous>:4:442)
    at $$writeModelToScope (http://dev.geojb/lib/angular.js:25047:5)
```

If I do a search in the source for `for (var i in` I get 5 matches, 4 in MeasureServices and 1 in DrawDirective. I also get 7 occurences in external lib. I'm afraid that any of them may cause trouble at one time or another. I'm affraid that modify the prototype of Array isn't worth it.

**Comment by gjn** [comment]
I tend to agree with @Jenselme . We should try to eliminate the overwriting of the Array object here: https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/profile/ProfileService.js#L137

**Comment by gjn** [comment]
btw: we could use d3.max and d3.min function instead of overwriting in profile service. I will create a PR.

**Comment by gjn** [comment]
That's not to say that we sholdn't address the `for i in array` expression, as _any_ library can extend the Array object. The beauty of JavaScript...

**Comment by oterral** [comment]
bad `for ... in` . I remove it all.

**Comment by gjn** [comment]
@oterral It's all in https://github.com/geoadmin/mf-geoadmin3/pull/2981

**Comment by oterral** [comment]
Thx
