### ISSUE TITLE
3D Iframe blocked with kml

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3015]
open win7 , use chrome

http://www.rts.ch/info/suisse/7349462-gagnants-ou-perdants-avec-le-nouvel-horaire-des-cff-partagez-votre-avis.html

activate 3d in iFrame

zoom pan arround with mouse and keyboard control
Result after a cuouple of movements :
3D crashes, with a win 11 warning,
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/11894850/47452006-a57a-11e5-9cc6-312197e3e71a.PNG)

**Comment by oterral** [comment]
```
Error: Blocked a frame with origin "https://map.geo.admin.ch" from accessing a cross-origin frame.
    at Error (native)
    at updateHeights (https://map.geo.admin.ch/src/lib/Cesium/Cesium.js:140434:62)
    at createRenderCommandsForSelectedTiles (https://map.geo.admin.ch/src/lib/Cesium/Cesium.js:140477:9)
    at QuadtreePrimitive.update (https://map.geo.admin.ch/src/lib/Cesium/Cesium.js:140074:13)
    at Globe.update (https://map.geo.admin.ch/src/lib/Cesium/Cesium.js:141302:21)
    at updatePrimitives (https://map.geo.admin.ch/src/lib/Cesium/Cesium.js:153500:26)
    at render (https://map.geo.admin.ch/src/lib/Cesium/Cesium.js:153568:9)
    at Scene.render (https://map.geo.admin.ch/src/lib/Cesium/Cesium.js:153610:13)
    at null.<anonymous> (https://map.geo.admin.ch/src/lib/ol3cesium-debug.js:42312:19)
    at goog.async.AnimationDelay.doAction_ (https://map.geo.admin.ch/src/lib/ol3cesium-debug.js:21418:18)

```

**Comment by davidoesch** [comment]
Another example http://www.skitourenguru.ch/index.php/routeview?ROUTE=Switzerland_Rauflihore_Egg.html&RISKIND=1.39&SERVER=http://www.skitourenguru.ch/calc_data

**Comment by oterral** [comment]
For skitourenguru website, the problem is that the page include  a KML (http://www.skitourenguru.ch/calc_data/kml/Switzerland_RiskRoute082.kml) with LineString(s) defined by one coordinate and Cesium doesn't allow that. If it's a LineString  there must be at least 2 coordinates.

**Comment by oterral** [comment]
@davidoesch can you warn the skitouren guru website ?

**Comment by davidoesch** [comment]
done

**Comment by davidoesch** [comment]
feedback from skitouren guru
"
Leider scheinen meine Multi-Geometrien nicht mit 3D zu harmonieren. Ich kann Ihnen versichern, dass jeder Line-String bei mir mindestens 2 Koordinaten aufweist (auch im von Ihnen genannten Beispiel). 
Ich habe verschiedenes probiert:
•	ClampToGround 
•	Extrude=0/1
"

**Comment by oterral** [comment]
The KMl has been corrected I guess

**Comment by oterral** [comment]
So now the 2 iframes have the same problem, any chance these websites use https?

**Comment by procrastinatio** [comment]
Dummy example:

[http parent page](http://dummy-geoadmin.s3-website-eu-west-1.amazonaws.com/rts.html)
[httpS parent page](https://dfa30utos8zzp.cloudfront.net/rts.html)

**Comment by oterral** [comment]
Seems a Cesium issue :  https://github.com/AnalyticalGraphicsInc/cesium/pull/3612
