### ISSUE TITLE
Node8  Error: Cannot find module 'readable-stream'

### ISSUE THREAD

**Issue by oterral** [geoadmin/mf-geoadmin3#4288]
When building geoadmin from scratch with node 8.9.1  this error occurs:
```
Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ltteo/mf-geoadmin3/node_modules/extract-zip/node_modules/concat-stream/index.js:1:78)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

```
readable-stream should be installed by other modules.

Workaround:
npm install readable-stream

**Comment by oterral** [comment]
Fixed by https://github.com/geoadmin/mf-geoadmin3/commit/fb188e2179b500ab0eb28212626947a500b96a2d#diff-b67911656ef5d18c4ae36cb6741b7965R765
