### ISSUE TITLE
mf-geoadmin build has been broken by greenkeeper upgrade

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#4458]
issue has been reported by @AFoletti 

building mf-geoadmin is not working anymore since this commit https://github.com/geoadmin/mf-geoadmin3/commit/f2a2c83bbf99dd176ee6b1471bf5988c41baac78

since then ``$ make user`` is failing

```bash
$ make user
....
test "https://pypi.org/simple/" != "https://pypi.org/simple/" && echo "https://pypi.org/simple/" > .build-artefacts/last-pypi-url || :
node_modules/.bin/eslint test/specs/ --fix
/home/ltclm/mf-geoadmin3/node_modules/eslint/lib/linter.js:739
                [methodName](...args) {
                             ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ltclm/mf-geoadmin3/node_modules/eslint/lib/cli-engine.js:21:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
Makefile:332: recipe for target 'linttest' failed
make[1]: *** [linttest] Error 1
make[1]: Leaving directory '/home/ltclm/mf-geoadmin3'
Makefile:277: recipe for target 'user' failed
make: *** [user] Error 2
```
@danduk82 @procrastinatio 
what is greenkeeper?
how can it happen that merging a greenkeeper upgrade is breaking the build script?
how can we avoid this in the future?

**Comment by loicgasser** [comment]
Greenkeeper is a bot that keeps the js lib up to date. In this case the problem is caused by eslint I believe. Try to revert to the precious eslint version in package.json

**Comment by ltclm** [comment]
thank you @loicgasser, good to know that you're keeping an eye on our issues 😌
