### ISSUE TITLE
3d: tlm2.5D layers are not flushed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4482]
Hi Andrea

The python script to flush the S3 cache for ch.swisstopo.swisstlm3d-karte-farbe.3d and ch.swisstopo.swisstlm3d-karte-grau.3d initially developed by @loicgasser  throws an error

Result:
ch.swisstopo.swisstlm3d-karte-farbe.3d can not be updated and hence the footprints of buildings are visibile https://s.geo.admin.ch/7cb65588a1

Expected result:
cache can be flushed and new  ch.swisstopo.swisstlm3d-karte-farbe.3d  can take effect

reported by @ltclm

**Comment by ltclm** [comment]
to reproduce:
```bash
./scripts/layer-prepare.sh ch.swisstopo.swisstlm3d-karte-farbe.3d all prod true 20 2

Creating tile for ch.swisstopo.swisstlm3d-karte-farbe.3d in prod                
Invalidating S3 bucket for ch.swisstopo.swisstlm3d-karte-farbe.3d in prod       
INFO:tool_aws.s3.rm:We will at most trigger 0 DELETE requests                   
INFO:tool_aws.s3.rm:Warning: the script will now start deleting:                
INFO:tool_aws.s3.rm:\n                                                          
            Number of keys: 64000                                               
            Chunk size    : 1000                                                
            Prefix        : /1.0.0/ch.swisstopo.swisstlm3d-karte-farbe.3d/default/current/
            Bucket name   : bgdi-tod-cache-prod       

INFO:tool_aws.s3.rm:result: {'ResponseMetadata': {'HostId': 'CVN63DsHNGQWIP2Mah1Zb+En7/5oOPzKl5Edf7miPT0UH3rrGSOZow4yBfmET51NobWHhRt3n20=', 'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '2F2EE0A8
ERROR:tool_aws.s3.rm:IncompleteRead(0 bytes read)                               
Traceback (most recent call last):                                              
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/tool_aws/s3/rm.py", line 293, in deleteKeys
    response = S3Bucket.delete_objects(Delete=keys)                             
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)                                    
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)            
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)                          
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)                                              
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)                    
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):                                               
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)               
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)                                       
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)                                                
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):                     
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)                                                           
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)            
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)                                                           
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)                                           
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception                                                      
IncompleteRead: IncompleteRead(0 bytes read)                                    
Traceback (most recent call last):                                              
  File ".venv/bin/s3rm", line 11, in <module>                                   
    sys.exit(main())                                                            
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/tool_aws/s3/rm.py", line 396, in main
    deleteWithPrefix(opts, S3Bucket, keys)                                      
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/tool_aws/s3/rm.py", line 371, in deleteWithPrefix
    callback=callback)                                                          
  File "/home/ltclm/automata_ltclm/.venv/local/lib/python2.7/site-packages/poolmanager/__init__.py", line 57, in imap_unordered
    raise Exception(e)                                                          
Exception: IncompleteRead(0 bytes read)                                         
Makefile:453: recipe for target 'prewarmlayer' failed                           
make: *** [prewarmlayer] Error 1  


```

**Comment by ltclm** [comment]
we have exactly the same issue with automata, have to find a solution asap

**Comment by ltclm** [comment]
automata error:
```bash
[2018-08-30 16:57:05]: start s3rm ch.swisstopo.pixelkarte-farbe-pk50.noscale 4326 2480000,1134000,2550000,1158000
INFO:tool_aws.s3.rm:We are about to trigger 143510 DELETE requests
INFO:tool_aws.s3.rm:Warning: the script will now start deleting:
INFO:tool_aws.s3.rm:\n
            Number of keys: 64000
            Chunk size    : 1000
            Prefix        : /1.0.0/ch.swisstopo.pixelkarte-farbe-pk50.noscale/default/current/4326/
            Bucket name   : bgdi-tod-cache-prod

INFO:tool_aws.s3.rm:Deletion started...
...
ERROR:tool_aws.s3.rm:IncompleteRead(0 bytes read)
Traceback (most recent call last):
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/tool_aws/s3/rm.py", line 293, in deleteKeys
    response = S3Bucket.delete_objects(Delete=keys)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
IncompleteRead: IncompleteRead(0 bytes read)
Traceback (most recent call last):
  File ".venv/bin/s3rm", line 11, in <module>
    sys.exit(main())
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/tool_aws/s3/rm.py", line 394, in main
    deleteWithBBox(opts, S3Bucket, keys)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/tool_aws/s3/rm.py", line 337, in deleteWithBBox
    callback=callback)
  File "/home/ltclm/automata_pk50_farbe/.venv/local/lib/python2.7/site-packages/poolmanager/__init__.py", line 57, in imap_unordered
    raise Exception(e)
Exception: IncompleteRead(0 bytes read)

```

**Comment by ltclm** [comment]
apparently not all tiles have been removed from s3
@hpchrist 
could you please launch a lifecycle delete request on this prefix:
``1.0.0/ch.swisstopo.swisstlm3d-karte-farbe.3d/default/current/``
on 
``bgdi-tod-cache-prod`` 
bucket?
Thank you!

**Comment by davidoesch** [comment]
Thanks Marcel for the effort.
Will await the life cycle delete by hp

**Comment by ltclm** [comment]
cache seems to be properly flushed and pre-heated now.
no need for lifecycle anymore.

**Comment by davidoesch** [comment]
Thx @ltclm for going this extra mile... Works now
